[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.219" , features = ["derive"] }
serde_json = "1.0.140"
image = { version = "0.25.6", features = [] }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
sha2 ="0.10.9"
