services:
  backend:
    image: mbround18/vtt-maps:v2-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MEILI_URL=http://meilisearch:7700
      - MEILI_KEY=${MEILI_MASTER_KEY:-masterKey}
      - REPO_REF=${REPO_REF:-main}
      - REPO_DIR=/data
    depends_on:
      - meilisearch
    volumes:
      - data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.14
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}


volumes:
  data: {}