[package]
name = "yew-frontend"
version = "0.1.0"
edition = "2024"


[dependencies]
shared = { path = "../shared" }
# you can check the latest version here: https://crates.io/crates/yew
yew = { version = "0.21.0" , features = ["csr"]}
yew-router = "0.18.0"
yew-hooks = "0.3.3"
gloo-net = "0.6.0"
reqwasm = "0.5.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
gloo-console = "0.3.0"
gloo-utils = "0.2.0"
gloo-file = "0.3.0"
web-sys = {version = "0.3.77", features = [
    "HtmlElement", 
    "HtmlCanvasElement", 
    "HtmlImageElement", 
    "CanvasRenderingContext2d",
    "Window",
    "MouseEvent",
    "WheelEvent",
    "DomRect"
]}
markdown="1.0.0"
base64 = "0.22.1"
urlencoding = "2.1.3"
pulldown-cmark = "0.13.0"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1.7"
