[package]
name = "yew-frontend"
version = "0.1.0"
edition = "2024"


[dependencies]
shared = { path = "../shared" }
# you can check the latest version here: https://crates.io/crates/yew
yew = { version = "0.21.0" , features = ["csr"]}
yew-router = "0.18.0"
yew-hooks = "0.3.3"
gloo-net = "0.6.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
gloo-console = "0.3.0"
web-sys = {version = "0.3.77", features = [
    "HtmlElement", 
    "HtmlCanvasElement", 
    "HtmlImageElement", 
    "CanvasRenderingContext2d",
    "Window",
    "MouseEvent",
    "WheelEvent",
    "DomRect"
]}
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1.7"

