apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - meilisearch.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vtt-maps
      app.kubernetes.io/part-of: vtt-maps-platform

replacements:
  - source:
      kind: ConfigMap
      name: vtt-maps-config
      fieldPath: data.REPO_REF
    targets:
      - select:
          kind: Deployment
          name: vtt-maps
        fieldPaths:
          - spec/template/spec/containers/0/env/2/value
