apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - meilisearch-deployment.yaml
  - meilisearch-service.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vtt-maps
      app.kubernetes.io/part-of: vtt-maps-platform

replacements:
  - source:
      kind: ConfigMap
      name: vtt-maps-config
      fieldPath: data.REPO_REF
    targets:
      - select:
          kind: Deployment
          name: vtt-maps
        fieldPaths:
          - spec/template/spec/containers/0/env/2/value
  - source:
      kind: Secret
      name: vtt-maps-secrets
      fieldPath: data.meili-key
    targets:
      - select:
          kind: Deployment
          name: vtt-maps
        fieldPaths:
          - spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/key
  - source:
      kind: ConfigMap
      name: vtt-maps-config
      fieldPath: data.GATEWAY_HOST
    targets:
      - select:
          kind: Gateway
          name: vtt-maps-gateway
        fieldPaths:
          - spec/servers/0/hosts/0
  - source:
      kind: Secret
      name: vtt-maps-secrets
      fieldPath: data.gateway-credential
    targets:
      - select:
          kind: Gateway
          name: vtt-maps-gateway
        fieldPaths:
          - spec/servers/0/tls/credentialName
  - source:
      kind: ConfigMap
      name: vtt-maps-config
      fieldPath: data.VIRTUAL_SERVICE_HOST
    targets:
      - select:
          kind: VirtualService
          name: vtt-maps-virtualservice
        fieldPaths:
          - spec/hosts/0