### Download map by ID
GET http://localhost:8080/api/maps/download/{{$dotenv MAP_ID}}
Accept: application/octet-stream

### Example with specific ID
GET http://localhost:8080/api/maps/download/b9a8748105a0442a2e7530c1737e24dfab6ace77d8722a1241947b4f0b370380
Accept: application/octet-stream
